export const FileType = {
  IMAGE: "IMAGE",
  VIDEO: "VIDEO",
  AUDIO: "AUDIO",
  DOCUMENT: "DOCUMENT",
  PDF: "PDF",
  PRESENTATION: "PRESENTATION",
  SPREADSHEET: "SPREADSHEET",
  ARCHIVE: "ARCHIVE",
  OTHER: "OTHER",
}
